// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/4/2024, 1:22:33 PM
const configMerger = require("C:/Users/Sofia Joy D. Yunun/Downloads/Nuxt-TodoApp/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/Sofia Joy D. Yunun/Downloads/Nuxt-TodoApp/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","C:/Users/Sofia Joy D. Yunun/Downloads/Nuxt-TodoApp/layouts/**/*.{vue,js,mjs}","C:/Users/Sofia Joy D. Yunun/Downloads/Nuxt-TodoApp/pages/**/*.{vue,js,mjs}","C:/Users/Sofia Joy D. Yunun/Downloads/Nuxt-TodoApp/composables/**/*.{js,ts,mjs}","C:/Users/Sofia Joy D. Yunun/Downloads/Nuxt-TodoApp/utils/**/*.{js,ts,mjs}","C:/Users/Sofia Joy D. Yunun/Downloads/Nuxt-TodoApp/{A,a}pp.{vue,js,mjs}","C:/Users/Sofia Joy D. Yunun/Downloads/Nuxt-TodoApp/{E,e}rror.{vue,js,mjs}","C:/Users/Sofia Joy D. Yunun/Downloads/Nuxt-TodoApp/app.config.{js,ts,mjs}"] } }));

module.exports = config
